name: 'slack-node-github-action'
description: 'A dead simple GitHub action that posts to your Slack using a secret.'
inputs:
  slackToken:
    description: 'The secret Slack token'
    required: true
  slackMessage:
    description: 'The actual Slack message to be sent'
    required: true
  environment:
    description: 'Allows you to change the enviroment (which might not be a good idea)'
    required: true
    default: 'production'
runs:
  using: 'node12'
  main: 'index.js'